/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData doc = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData font = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData android = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData music_note =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData video = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData android_1 =
      const IconData(0xf17b, fontFamily: _kFontFam);
  static const IconData file_pdf =
      const IconData(0xf1c1, fontFamily: _kFontFam);
  static const IconData file_excel =
      const IconData(0xf1c3, fontFamily: _kFontFam);
  static const IconData file_powerpoint =
      const IconData(0xf1c4, fontFamily: _kFontFam);
  static const IconData file_archive =
      const IconData(0xf1c6, fontFamily: _kFontFam);
  static const IconData question_circle_o =
      const IconData(0xf29c, fontFamily: _kFontFam);
}
