name: CI

on:
  push:
    paths: 
      - '*'
      - '!*.md'
      - '!/docs/*'

jobs:
    build:
      runs-on: ubuntu-latest
      name: build
      steps:
        - name: Set up Checkout branch
          uses: actions/checkout@v1
        - name: Set up Java
          uses: actions/setup-java@v1
          with: 
            java-version: '12.x'
        - name: Set up Flutter
          uses: subosito/flutter-action@v1
          with:
            channel: 'stable'
        - name: Setting up flutter
        # Set up flutter on master channel to allow for desktop testing/building
          run: |
            flutter channel master 
            flutter upgrade
            flutter config --enable-web --enable-linux-desktop
            flutter precache --{web,linux}
            flutter pub get

    test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Integration Tests
          run: flutter test --coverage test/*_test.dart

    coverage:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Coveralls
          uses: coverallsapp/github-action@v1.0.1
          with:
            github-token: ${{ sercets.github-token }}
            path-to-lcov: ./coverage/lcov.info
    
