name: Release


on: [release]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Building for Android
        run: echo Building for Android

jobs:
  name: Publish
  needs: Build
  runs-on: ubuntu-latest
  steps:
    - name: TEMP
      run: echo TEMP
